In [32]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

In [33]:
df = pd.read_csv(r"dataset\manufacturing_dataset.csv")

In [34]:
df.head(5)

,time_stamp,machine_ID,operation_mode,temperature,vibration,power_consumption,network_latency,packet_loss,defect_rate,speed,pm_score,error_rate,efficiency_status
0,1/1/2024 0:00,39,Idle,74.137590,3.500595,8.612162,10.650542,0.207764,7.751261,477.657391,0.344650,14.965470,Low
1,1/1/2024 0:01,29,Active,84.264558,3.355928,2.268559,29.111810,2.228464,4.989172,398.174747,0.769848,7.678270,Low
2,1/1/2024 0:02,15,Active,44.280102,2.079766,6.144105,18.357292,1.639416,0.456816,108.074959,0.987086,8.198391,Low
3,1/1/2024 0:03,43,Active,40.568502,0.298238,4.067825,29.153629,1.161021,4.582974,329.579410,0.983390,2.740847,Medium
4,1/1/2024 0:04,8,Idle,75.063817,0.345810,6.225737,34.029191,4.796520,2.287716,159.113525,0.573117,12.100686,Low

In [35]:
df['time_stamp'] = pd.to_datetime(df['time_stamp']).dt.date

In [36]:
df = df[['time_stamp','operation_mode','defect_rate','speed']]
df

       time_stamp operation_mode  defect_rate       speed
0      2024-01-01           Idle     7.751261  477.657391
1      2024-01-01         Active     4.989172  398.174747
2      2024-01-01         Active     0.456816  108.074959
3      2024-01-01         Active     4.582974  329.579410
4      2024-01-01           Idle     2.287716  159.113525
...           ...            ...          ...         ...
99995  2024-03-10           Idle     2.823803  282.822791
99996  2024-03-10           Idle     6.065958  466.696532
99997  2024-03-10         Active     5.090971  324.277200
99998  2024-03-10         Active     8.333964   65.965864
99999  2024-03-10         Active     3.680996  231.469437

[100000 rows x 4 columns]

In [ ]:
df['up_time'] = df['operation_mode'].apply(lambda r: 1) # in minute
df

       time_stamp operation_mode  defect_rate       speed  up_time
0      2024-01-01           Idle     7.751261  477.657391        1
1      2024-01-01         Active     4.989172  398.174747        1
2      2024-01-01         Active     0.456816  108.074959        1
3      2024-01-01         Active     4.582974  329.579410        1
4      2024-01-01           Idle     2.287716  159.113525        1
...           ...            ...          ...         ...      ...
99995  2024-03-10           Idle     2.823803  282.822791        1
99996  2024-03-10           Idle     6.065958  466.696532        1
99997  2024-03-10         Active     5.090971  324.277200        1
99998  2024-03-10         Active     8.333964   65.965864        1
99999  2024-03-10         Active     3.680996  231.469437        1

[100000 rows x 5 columns]

In [ ]:
df = df.groupby(['time_stamp','operation_mode']).agg({
    'defect_rate':'mean',
    'speed':'mean',
    'up_time':'sum'
}).reset_index()
df

     time_stamp operation_mode  defect_rate       speed
0    2024-01-01         Active     5.017490  273.035277
1    2024-01-01           Idle     5.004306  267.705500
2    2024-01-01    Maintenance     5.026892  293.606808
3    2024-01-02         Active     5.225992  278.136684
4    2024-01-02           Idle     5.077460  270.401504
..          ...            ...          ...         ...
205  2024-03-09           Idle     5.011936  271.668617
206  2024-03-09    Maintenance     5.218970  275.513772
207  2024-03-10         Active     4.969501  268.936751
208  2024-03-10           Idle     4.517953  271.610526
209  2024-03-10    Maintenance     4.683326  276.934921

[210 rows x 4 columns]